models/Cargo.php
<?php

namespace app\models;

use Yii;
use app\helpers\HelperStr;
use yii\helpers\HtmlPurifier;

/**
 * This is the model class for table "cargo".
 *
 * @property integer $cargo_id
 * @property integer $shipment_id
 * @property integer $date_add
 * @property integer $date_received
 * @property integer $from_id
 * @property integer $to_id
 * @property integer $date_given_to_client
 * @property integer $delivery_time
 * @property integer $client_id
 * @property integer $manager_id
 * @property integer create_manager_id
 * @property integer $project_id
 * @property integer $warehouse_id
 * @property integer $shipment_type_id
 * @property integer $status_id
 * @property double $weight
 * @property double $volume
 * @property integer $cartons
 * @property double $volume_weight
 * @property integer $count_inside
 * @property string $local_track
 * @property double $local_delivery_price
 * @property string $local_expenses
 * @property string $track
 * @property integer $type_id
 * @property integer $type_special_id
 * @property integer $status
 * @property string $description
 * @property string $photos
 * @property string $invoice
 * @property string $file
 * @property integer $site
 */
class Cargo extends \yii\db\ActiveRecord
{
    public $file1;
    public $file2;
    public $file3;
    ///////
    public $row_shipment_type_id = '';
    public $row_shipment_id = '';
    public $row_status_id = '';
    ///////
    public $row_warehouse_id = '';
    ///////
    public $row_status_count = 0;
    public $row_weight = 0;
    public $row_volume = 0;
    public $row_volume_weight = 0;
    public $row_cartons = 0;
    public $row_count = 0;
    ///////
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'cargo';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['cargo_id','shipment_id','date_add','date_received','from_id','to_id','date_given_to_client', 'delivery_time', 'client_id', 'manager_id', 'project_id', 'warehouse_id', 'shipment_type_id', 'status_id','weight','volume','cartons','volume_weight','count_inside','local_track','local_delivery_price','local_expenses','track','type_id','type_special_id','status' ,'description','photos','invoice','file','site'],'filter','filter'=>'\yii\helpers\HtmlPurifier::process'],
            
            [['status_id', 'weight', 'volume', 'cartons'], 'required'],
            [['shipment_id', 'date_add', 'date_received', 'from_id', 'to_id', 'date_given_to_client', 'delivery_time', 'client_id', 'manager_id', 'create_manager_id', 'project_id', 'warehouse_id', 'shipment_type_id', 'status_id', 'cartons', 'count_inside', 'type_id','type_special_id', 'status', 'site'], 'integer'],
            [['weight', 'volume', 'volume_weight', 'local_delivery_price'], 'number'],
            [['photos', 'invoice', 'file', 'local_track', 'track', 'description','local_expenses'], 'string'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'cargo_id' => 'Cargo code',
            'shipment_id' => 'Shipment',
            'date_add' => 'Date Add',
            'date_received' => 'Date received',
            'from_id' => 'From ID',
            'to_id' => 'To ID',
            'date_given_to_client' => 'Date Given To Client',
            'delivery_time' => 'Delivery Time',
            'client_id' => 'Client ID',
            'manager_id' => 'Manager',
            'create_manager_id' => 'Manager created',
            'project_id' => 'Project',
            'warehouse_id' => 'Checkpoint',
            'shipment_type_id' => 'Shipment type',
            'status_id' => 'Status',
            'weight' => 'Weight',
            'volume' => 'Volume',
            'cartons' => 'Cartons',
            'volume_weight' => 'Volume weight',
            'count_inside' => 'Qty inside',
            'local_track' => 'Local tracking',
            'local_delivery_price' => 'Local Delivery Price',
            'local_expenses' => 'Local Additional Expenses',
            'track' => 'Track',
            'type_id' => 'Cargo type',
            'type_special_id' => 'Type special',
            'status' => 'Status',
            'description' => 'Description',
            'photos' => 'Photos',
            'invoice' => 'Invoice',
            'file' => 'File',
            'site' => 'Site',
        ];
    }

    public function getManager()
    {
        return $this->hasOne(Manager::className(), ['manager_id' => 'manager_id']);
    }

    public function getManagerCreate()
    {
        return $this->hasOne(Manager::className(), ['manager_id' => 'create_manager_id']);
    }

    public function getShipmentType()
    {
        return $this->hasOne(ShipmentType::className(), ['type_id' => 'shipment_type_id']);
    }

    public function getShipment()
    {
        return $this->hasOne(Shipment::className(), ['shipment_id' => 'shipment_id']);
    }

    public function getCargoStatus()
    {
        return $this->hasOne(CargoStatus::className(), ['status_id' => 'status_id']);
    }

    public function getFrom()
    {
        return $this->hasOne(Country::className(), ['country_id' => 'from_id']);
    }

    public function getTo()
    {
        return $this->hasOne(Country::className(), ['country_id' => 'to_id']);
    }

    public function getWarehouse()
    {
        return $this->hasOne(Stock::className(), ['stock_id' => 'warehouse_id']);
    }

    public function getType()
    {
        return $this->hasOne(CargoType::className(), ['type_id' => 'type_id']);
    }

    static function special_types(){
        return array(1 => 'Mobile', 4 => 'Liquid', 5 => 'Powder', 6 => 'Battery'); //2 => 'DG Cargo (battery)', 3 => 'Brands', 
    }

    public function special_type($id){
        switch ($id) {
            case 1:
                return Cargo::special_types()[1];
                break;
            // case 2:
            //     return Cargo::special_types()[2];
            //     break;
            // case 3:
            //     return Cargo::special_types()[3];
            //     break;
            case 4:
                return Cargo::special_types()[4];
                break;
            case 5:
                return Cargo::special_types()[5];
                break;
            case 6:
                return Cargo::special_types()[6];
                break;
            default:
                return '';
                break;
        }
    }

    public function uploadFile($file, $path = ''){
        if(!empty($_FILES[$file]['tmp_name'])){
            $info = pathinfo($_FILES[$file]['name']);
            $ext = $info['extension']; // get the extension of the file
            if($ext != 'html' && $ext != 'php'){
                $newname = time().HelperStr::randomText(5, 'string', 'int').".".$ext; 

                $target = '/home/inta/crm.inta.group/public_html/uploads/'.$path.$newname;
                move_uploaded_file( $_FILES[$file]['tmp_name'], $target);
                return '/uploads/'.$path.$newname;
            }
        }
        return '';
    }

    public function uploadFiles($file, $path = ''){
        $all_files = '';
        if(isset($_FILES[$file]['name'])){
            for($file_count=0; $file_count < count($_FILES[$file]['name']); $file_count++){
                $info = pathinfo($_FILES[$file]['name'][$file_count]);
                $ext = $info['extension']; // get the extension of the file
                if($ext != 'html' && $ext != 'php'){
                    $newname = time().HelperStr::randomText(5, 'string', 'int').".".$ext; 

                    $target = '/home/inta/crm.inta.group/public_html/uploads/'.$path.$newname;
                    move_uploaded_file( $_FILES[$file]['tmp_name'][$file_count], $target);
                    if($all_files != ''){
                        $all_files .= ',';
                    }
                    $all_files .= '/uploads/'.$path.$newname;
                }
            }
        }
        return $all_files;
    }

    static function currentCargos(){
        return Cargo::find()->where(['manager_id'=>Yii::$app->user->identity->id])->andWhere('date_received >= '.strtotime('01'.date('.m.Y ').'00:00:00'))->count();
    }

    static function currentCargosKg(){
        $summ = 0;
        $allCargos = Cargo::find()->where(['manager_id'=>Yii::$app->user->identity->id])->andWhere('date_received >= '.strtotime('01'.date('.m.Y ').'00:00:00'))->all();
        foreach ($allCargos as $cargo) {
            $summ += $cargo->weight;
        }
        return $summ;
    }

    static function cargoDropMenu($name, $code, $type = 0, $placeholder = ''){
        $input = '';
        $btns_sort = '';
        $dropdown = '<div class="dropdown-divider"></div>
                      <a class="dropdown-item dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">'.$placeholder.'</a>
                      <div class="dropdown-menu dropdown-menu-table dropdown-menu-table-scroll" aria-labelledby="navbarDropdownMenuLink">';
        switch ($type) {
            case 'text':
                $input = '<input type="text" class="dropdown-item dropdown-search-input" placeholder="'.$placeholder.'" data-type="'.$code.'">';
                break;
            case 'date':
                $input = '<input type="text" class="dropdown-item dropdown-search-input" id="form-choose-date" placeholder="'.$placeholder.'" data-type="'.$code.'">';
                break;
            case 'select':
                switch ($code) {
                    case 'manager_id':
                        $managers = Manager::find()->all();
                        if(isset($managers)){
                            $input .= $dropdown;
                            foreach ($managers as $manager) {

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;

use yii\helpers\Html;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\web\Controller;

use app\models\Login;
use app\models\Telegram;
use app\models\Manager;
use app\models\Cargo;
use app\models\Client;
use app\models\Payments;
use app\models\Plan;
use app\models\Task;



class SiteController extends Controller
{
    public $enableCsrfValidation = false;
    
    //public function behaviors()
    //{
    //    return [
    //        'access' => [
    //            'class' => AccessControl::className(),
    //            'only' => ['logout'],
    //            'rules' => [
    //                [
    //                    'actions' => ['logout'],
    //                    'allow' => true,
    //                    'roles' => ['@'],
    //                ],
    //            ],
    //        ],
    //        'verbs' => [
    //            'class' => VerbFilter::className(),
    //            'actions' => [
    //                'logout' => ['post'],
    //            ],
    //        ],
    //    ];
    //}

    public function actions()
    {

        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function beforeAction($action)
    {
        if(Yii::$app->user->isGuest){
            return true;
        }
        if (Yii::$app->user->identity->role >= 4){
            return true;
        }
        else if($action->id == 'logout'){
            return true;
        }
        elseif (Yii::$app->user->identity->role == 2){
            Yii::$app->getResponse()->redirect('/clients/index');
            return false;
        }else{
            Yii::$app->getResponse()->redirect('/website');
            return false;
        }
        return true;
        // if($action->id == 'login'){
        //     return true;
        // }

        // if (!parent::beforeAction($action))
        // {
        //     return false;
        // }


        // else
        // {
        //     Yii::$app->getResponse()->redirect(Yii::$app->getHomeUrl());
        //     //для перестраховки вернем false
        //     return false;
        // }
    }

    public function actionResources(){
        return $this->render('/bogdan/resources');
    }
    

    // public function actionIndex()
    // {
    //     if(Yii::$app->user->identity->role <= 5){
    //         return $this->redirect('/cargo/index');
    //     }

    //     $user = Manager::findOne(Yii::$app->user->identity->id);
    //     $current_sales = Payments::currentSales();
    //     $current_clients = Client::currentClients();
    //     $current_cargos = Cargo::currentCargos();
    //     $current_cargos_kg = Cargo::currentCargosKg();
    //     $plan = Plan::findOne(['manager_id'=>$user->manager_id,'date'=>strtotime(date('Y-m-2', time()))]);

    //     if(Yii::$app->user->identity->role >= 9){
    //         $cargos = Cargo::find()
    //         ->where(['status'=>1])
    //         ->orderBy(['cargo_id' => SORT_DESC])
    //         ->limit(20)
    //         ->all();
    //     }
    //     else{
    //         $cargos = Cargo::find()
    //         ->where(['status'=>1, 'manager_id'=>Yii::$app->user->identity->id])
    //         ->orderBy(['cargo_id' => SORT_DESC])
    //         ->limit(20)
    //         ->all();
    //     }

    //     if(isset($cargos)){
    //         $all_table_rows = '';
    //         foreach ($cargos as $cargo) {
    //             $all_table_rows .= Yii::$app->controller->renderPartial('/cargo/one_table', [
    //                 'cargo'=>$cargo,
    //             ]);
    //         }
    //     }
    //     else{
    //         $all_table_rows = 'У вас нет Cargo!';
    //     }

    //     if(Yii::$app->user->identity->role >= 9){
    //         $clients = Client::find()
    //         ->orderBy(['status'=>[0,1], 'client_id' => SORT_DESC])
    //         ->limit(20)
    //         ->all();
    //     }
    //     else{
    //         $clients = Client::find()
    //         ->where(['status'=>[0,1], 'manager_id'=>Yii::$app->user->identity->id])
    //         ->orderBy(['client_id' => SORT_DESC])
    //         ->limit(20)
    //         ->all();
    //     }

    //     if(isset($clients)){
    //         $all_table_rows_clients = '';
    //         foreach ($clients as $client) {
    //             $all_table_rows_clients .= Yii::$app->controller->renderPartial('/clients/one_table', [
    //                 'client'=>$client,
    //             ]);
    //         }
    //     }
    //     else{
    //         $all_table_rows_clients = 'У вас нет Clients!';
    //     }

    //     return $this->render('index', [
    //         'all_table_rows' => $all_table_rows,
    //         'all_table_rows_clients' => $all_table_rows_clients,
    //         'user' => $user,
    //         'plan' => $plan,
    //         'current_sales' => $current_sales,
    //         'current_clients' => $current_clients,
    //         'current_cargos' => $current_cargos,
    //         'current_cargos_kg' => $current_cargos_kg,
    //     ]);
    // }

    public function actionIndex()
    {

        $tasks = Task::find()
            ->filterWhere(['=', 'manager_id', Yii::$app->user->identity->id])
            ->andFilterWhere(['=', 'status', 0])
            ->orderBy(['date_end' => SORT_ASC])
            ->all();


        /* Another part  */
        if(Yii::$app->user->identity->role <= 5){
            return $this->redirect('/cargo/index');
        }

        $user = Manager::findOne(Yii::$app->user->identity->id);
        $current_sales = Payments::currentSales();
        $current_clients = Client::currentClients();
        $current_cargos = Cargo::currentCargos();
        $current_cargos_kg = Cargo::currentCargosKg();
        $plan = Plan::findOne(['manager_id'=>$user->manager_id,'date'=>strtotime(date('Y-m-2', time()))]);

        return $this->render('new_index', [
            'user' => $user,
            'plan' => $plan,
            'current_sales' => $current_sales,
            'current_clients' => $current_clients,
            'current_cargos' => $current_cargos,
            'current_cargos_kg' => $current_cargos_kg,
            'tasks' => $tasks,
        ]);
    }

    public function actionMoney()
    {
        if(Yii::$app->user->isGuest){
            return $this->redirect(['site/login']);
        }
        return $this->redirect(['site/index']);
        //if (Yii::$app->request->post('money') && !empty((int)Yii::$app->request->post('money'))){
        //    $user = Users::findOne(Yii::$app->user->identity->id);
        //    $user->money += (int)Yii::$app->request->post('money');
        //    $user->update(false);
        //}
        $user = Users::findOne(Yii::$app->user->identity->id);
        return $this->render('money',['user'=>$user]);
    }

    public function actionLogin()
    {
      if (!Yii::$app->user->isGuest) {
          return $this->goHome();
      }
      
      $login = new Login();
      
      if (Yii::$app->request->post('Login')) {
          $login->attributes = Yii::$app->request->post('Login');
      
          if ($login->validate()){
              Yii::$app->user->login($login->getUser(), 3600*24*30);
              return $this->redirect('/index');
              //return $this->goBack();
          }
      }
      
      return Yii::$app->controller->renderPartial('login', [
          'login'=>$login,
      ]);
    }

    public function actionLogout()
    {
        if(Yii::$app->user->isGuest){
            return $this->redirect(['site/login']);
        }

        Yii::$app->user->logout();

        return $this->goHome();
    }


    
}

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/login.php
<?php
  use yii\helpers\Html;
?>

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Login | INTA.GROUP</title>

    <meta charset="<?= Yii::$app->charset ?>">
    <?= Html::csrfMetaTags() ?>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="Login to the CPM Office" name="description">
    <!-- Facebook Opengraph integration: https://developers.facebook.com/docs/sharing/opengraph -->
    <meta property="og:title" content="Login | INTA.GROUP">
    <meta property="og:image" content="/web/img/logo_black.jpg">
    <meta property="og:site_name" content="Login | INTA.GROUP">
    <meta property="og:description" content="Login to the CPM Office">
    
    <!-- Twitter Cards integration: https://dev.twitter.com/cards/  -->
    <meta name="twitter:card" content="summary">
    <meta name="twitter:site" content="Login | INTA.GROUP">
    <meta name="twitter:title" content="Login | INTA.GROUP">
    <meta name="twitter:description" content="Login to the CPM Office">
    <meta name="twitter:image" content="/web/img/logo_black.jpg">

    <link rel="stylesheet" href="/web/css/main_2.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="crossorigin="anonymous"></script>
</head>

<body>
    <div class="overlay flex cac vac ">
        <div>
            <div class="loader preloader flex vac">
                <svg width="200" height="200">
                    <circle class="background" cx="90" cy="90" r="80" transform="rotate(-90, 100, 90)" />
                    <circle class="outer" cx="90" cy="90" r="80" transform="rotate(-90, 100, 90)" />
                </svg>
                <span class="circle-background"></span>
                <span class="logo animated fade-in"></span>
            </div>
        </div>
    </div>
    <header class="login-page">
        <div class="container">
            <div class="content-wrap row">

                <div class="logo col-lg-7 col-md-12">
                    <img src="/web/img/logo.png" alt="">
                </div>

                <div class="login-page-form-wrap col-lg-5 col-md-12">
                    <div class="login-page-form-title">Войдите для доступа<br />к CrM INTA</div>
                    <form action="/login" method="post">
                        <div class="input-wrap">
                            <span><i class="fas fa-user"></i></span>
                            <input type="text" name="Login[username]" placeholder="Логин" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Логин'">
                        </div>
                        <div class="input-wrap">
                            <span><i class="fas fa-lock"></i></span>
                            <input type="password" name="Login[password]" placeholder="Пароль" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Пароль'">
                            <!-- <div class="forget-pass">
                                <a href="#">Забыли пароль?</a>
                            </div> -->
                        </div>
                        <div class="input-wrap-checkbox">
                            <label for="remember" class="custom-input">
                                <input type="checkbox" id='remember'>
                                <span class="checkmark"></span>
                                 Не запоминать
                            </label>
                        </div>
                        <div class="input-wrap-button">
                            <input type="hidden" name="_csrf" value="<?=Yii::$app->request->getCsrfToken()?>" />
                            <input type="submit" name="submit" value="войти">
                        </div>
                    </form>

                    <div class="markets-links">
                        <a href="#"><img src="/web/img/appstore.jpg" alt="#"></a>
                        <a href="#"><img src="/web/img/google-play.jpg" alt="#"></a>
                    </div>

                </div>

                <div class="login-page-footer">
                    © 2018 «inta.group»
                </div>

            </div>
        </div>

    </header>
    <script defer src="https://use.fontawesome.com/releases/v5.5.0/js/all.js" integrity="sha384-GqVMZRt5Gn7tB9D9q7ONtcp4gtHIUEW/yG7h98J7IpE3kpi+srfFyyB/04OV6pG0" crossorigin="anonymous"></script>
    <script src="https://code.highcharts.com/highcharts.src.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="/web/libs/datetimepicker-master/jquery.datetimepicker.full.min.js"></script>
    <script src="/web/libs/phone/build/js/intlTelInput.min.js"></script>
    <script type="text/javascript">
        var input = document.querySelector("#choose-phone");
        window.intlTelInput(input, {
            separateDialCode: true,
        });
    </script>
    <!-- <script src="/web/js/main_1.js"></script> -->
    <script src="/web/js/main_4.js"></script>
    <script src="/web/js/chart.js"></script>
</body>

</html>
<?php $this->endPage() ?>

views/site/money.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Пополнение баланса';
// $this->params['breadcrumbs'][] = $this->title;
?>
<section class="container sectionEditOrder">
    <p class="h2 text-center slimText">
        ПОПОЛНЕНИЕ БАЛАНСА
    </p>
    <div class="row" id="order1">
        <form id="login-form" class="form-horizontal" action="/money" method="post">
            <div class="col-xs-12 col-sm-12 col-lg-12">
                <div style="font-size: 30px;font-weight: 100;">
                    ВАШ БАЛАНС - 
                    <span style="font-weight: 400;"><?=$user->money?></span>
                    $
                </div>  
            </div>
            <div class="col-xs-12 col-sm-12 col-lg-12">
                <input type="text" required="" name="money" placeholder="Сумма - 100$" value="" id="money">  
            </div>
            <div class="col-xs-12 col-sm-12 col-lg-12"> 
                <button class="submitBTN" style="width: 100%;cursor: not-allowed;" disabled="disabled">
                    ПОПОЛНИТЬ
                </button>
            </div>
        </form>
    </div>
</section>

views/site/order_one.php
<?php
    use app\models\Orders;
    $orderController = new Orders;
    if($order->shipment_type == 'Post'){
        $order->shipment_type = 'Air+Freight';
    }
?>

<tr>
    <td class="way">
        <i class="sprite <?= $orderController->location($order->location_from) ?>" title="<?= $order->location_from ?>"></i>
        <i class="sprite <?= $orderController->type_shipment($order->shipment_type) ?>" title="<?= $order->shipment_type ?>"></i>
        <i class="sprite <?= $orderController->location($order->location_to) ?>" title="<?= $order->location_to ?>"></i>
    </td>
    <td>
        <?= $order->code_cc ?>
    </td>
    <td>
        <?= $order->date_received ?>
    </td>
    <td>
        <?= $order->warehouse ?>
    </td>
    <td>
        <?= $order->status ?>
    </td>
    <td>
        <?= $order->weight ?>
    </td>
    <td>
        <?= $order->volume ?>
    </td>
    <td>
        <?= $order->cartons ?>
    </td>
    <td>
        <?= $order->description ?>
    </td>
    <td>
        <?= $order->local_tracking ?>
    </td>
</tr>