models/Project.php
<?php

namespace app\models;

use Yii;
use app\models\ShipmentType;
use app\models\Payments;
use yii\helpers\HtmlPurifier;

/**
 * This is the model class for table "project".
 *
 * @property integer $project_id
 * @property integer $manager_id
 * @property integer $client_id
 * @property string $name
 * @property integer $date_create
 * @property integer $date_close
 * @property integer $project_type
 * @property integer $delivery_type
 * @property string $comment
 * @property string $total
 * @property string $profit
 * @property string $payed
 * @property string $must_pay
 * @property string $chargers
 * @property string $plan_bonuse
 * @property string $cargo_cost
 * @property string $insurance
 * @property string $insurance_sum
 * @property integer $status
 */
class Project extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'project';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['project_id','manager_id','client_id','name','date_create','date_close','project_type', 'delivery_type', 'comment', 'total', 'profit','payed','must_pay', 'chargers', 'plan_bonuse', 'cargo_cost', 'insurance', 'insurance_sum','status','buying_id'],'filter','filter'=>'\yii\helpers\HtmlPurifier::process'],
            
            [['client_id', 'project_type', 'total', 'profit', 'status'], 'required'],
            [['client_id', 'manager_id', 'date_create', 'date_close', 'project_type', 'delivery_type', 'status','buying_id'], 'integer'],
            [['comment'], 'string'],
            [['total', 'profit','payed','must_pay', 'chargers', 'plan_bonuse', 'cargo_cost', 'insurance', 'insurance_sum'], 'number'],
            [['name'], 'string', 'max' => 30],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'project_id' => 'Project ID',
            'manager_id' => 'Manager',
            'client_id' => 'Client ID',
            'name' => 'Project Name',
            'date_create' => 'Created',
            'date_close' => 'Closed',
            'project_type' => 'Type',
            'delivery_type' => 'Delivery',
            'comment' => 'Comments',
            'total' => 'Total',
            'profit' => 'Profit',
            'payed' => 'Payed',
            'must_pay' => 'Must Pay',
            'chargers' => 'Chargers',
            'plan_bonuse' => 'Plan Bonuse',
            'cargo_cost' => 'Cargo Cost',
            'insurance' => 'Insurance',
            'insurance_sum' => 'Insurance Sum',
            'status' => 'Status',
            'buying_id' => 'Buying ID',
        ];
    }

    static function types(){
        return array(1 => 'Delivery', 2 => 'Money Transfer', 3 => 'Buying', 4 => 'Customs clearance');
    }

    public function type($id){
        switch ($id) {
            case 1:
                return Project::types()[1];
                break;
            case 2:
                return Project::types()[2];
                break;
            case 3:
                return Project::types()[3];
                break;
            case 4:
                return Project::types()[4];
                break;
            default:
                return 'No type';
                break;
        }
    }

    public function getManager()
    {
        return $this->hasOne(Manager::className(), ['manager_id' => 'manager_id']);
    }

    public function getDevivery()
    {
        return $this->hasOne(Manager::className(), ['manager_id' => 'manager_id']);
    }

    public function getShipmentType()
    {
        return $this->hasOne(ShipmentType::className(), ['type_id' => 'delivery_type']);
    }

    public function getClient()
    {
        return $this->hasOne(Client::className(), ['client_id' => 'client_id']);
    }

    public function getBuying()
    {
        return $this->hasOne(BuyingList::className(), ['buying_id' => 'buying_id']);
    }

    static function projectDropMenu($name, $code, $type = 0, $placeholder = ''){
        $input = '';
        $btns_sort = '';
        $dropdown = '<div class="dropdown-divider"></div>
                      <a class="dropdown-item dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">'.$placeholder.'</a>
                      <div class="dropdown-menu dropdown-menu-table dropdown-menu-table-scroll" aria-labelledby="navbarDropdownMenuLink">';
        switch ($type) {
            case 'text':
                $input = '<input type="text" class="dropdown-item dropdown-search-input" placeholder="'.$placeholder.'" data-type="'.$code.'">';
                break;
            case 'date':
                $input = '<input type="text" class="dropdown-item dropdown-search-input" id="form-choose-date" placeholder="'.$placeholder.'" data-type="'.$code.'">';
                break;
            case 'date2':
                $input = '<input type="text" class="dropdown-item dropdown-search-input" id="form-choose-date-2" placeholder="'.$placeholder.'" data-type="'.$code.'">';
                break;
            case 'select':
                switch ($code) {
                    case 'manager_id':
                        $managers = Manager::find()->all();
                        if(isset($managers)){
                            $input .= $dropdown;
                            foreach ($managers as $manager) {
                                $input .= '<a class="dropdown-item search-menu-click" tabindex="-1" data-type="'.$code.'" data-id="'.$manager->manager_id.'">'.$manager->username.'</a>';
                            }
                            $input .= '</div>';
                        }
                        break;
                    case 'project_type':
                        $types = Project::types();
                        if(isset($types)){
                            $input .= $dropdown;
                            foreach ($types as $type_key => $type_name) {
                                $input .= '<a class="dropdown-item search-menu-click" data-type="'.$code.'" data-id="'.$type_key.'">'.$type_name.'</a>';
                            }
                            $input .= '</div>';
                        }
                        break;
                    case 'delivery_type':
                        $types_delivery = ShipmentType::find()->all();
                        if(isset($types_delivery)){
                            $input .= $dropdown;
                            foreach ($types_delivery as $type_delivery) {
                                $input .= '<a class="dropdown-item search-menu-click" data-type="'.$code.'" data-id="'.$type_delivery->type_id.'">'.$type_delivery->name.'</a>';
                            }
                            $input .= '</div>';
                        }
                        break;
                }
                break;
        }
        if($code != 'comment'){
            $btns_sort = '<a class="dropdown-item" href="?sort='.$code.'">Sort by Asc</a><a class="dropdown-item" href="?sort=-'.$code.'">Sort by Desc</a>';
        }

        return '<div class="dropdown dropdown-table">
                    <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      '.$name.'
                    </a>
                    <div class="dropdown-menu dropdown-menu-table" aria-labelledby="dropdownMenuLink">
                      '.$btns_sort.'
                      '.$input.'
                    </div>
                </div>';
    }

    static function SearchSession(){
        $session = Yii::$app->session;

        if(Yii::$app->request->get('project_id')){
            $session['project_project_id'] = (int)str_replace('PAY-', '', Yii::$app->request->get('project_id'));
        }
        if(Yii::$app->request->get('manager_id')){
            $session['project_manager_id'] = Yii::$app->request->get('manager_id');
        }
        if(Yii::$app->request->get('client_id')){
            $session['project_client_id'] = (int)str_replace('88-', '', Yii::$app->request->get('client_id'));
        }
        if(Yii::$app->request->get('date_create')){
            $session['project_date_create'] = (int)strtotime(Yii::$app->request->get('date_create'));
        }
        if(Yii::$app->request->get('date_close')){
            $session['project_date_close'] = (int)strtotime(Yii::$app->request->get('date_close'));
        }
        if(Yii::$app->request->get('project_type')){
            $session['project_project_type'] = Yii::$app->request->get('project_type');
        }
        if(Yii::$app->request->get('delivery_type')){
            $session['project_delivery_type'] = Yii::$app->request->get('delivery_type');
        }
        if(Yii::$app->request->get('name')){
            $session['project_name'] = Yii::$app->request->get('name');
        }
        if(Yii::$app->request->get('comment')){
            $session['project_comment'] = Yii::$app->request->get('comment');
        }
        if(isset($_GET['total'])){
            $session['project_total'] = (int)$_GET['total'];
        }
        if(isset($_GET['profit'])){
            $session['project_profit'] = (int)$_GET['profit'];
        }
        if(isset($_GET['payed'])){
            $session['project_payed'] = (int)$_GET['payed'];
        }
        if(isset($_GET['must_pay'])){
            $session['project_must_pay'] = (int)$_GET['must_pay'];
        }
        if(isset($_GET['chargers'])){
            $session['project_chargers'] = (int)$_GET['chargers'];
        }
        if(isset($_GET['plan_bonuse'])){
            $session['project_plan_bonuse'] = (int)$_GET['plan_bonuse'];
        }
        if(Yii::$app->request->get('buying_id')){

views/projects/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Project */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="project-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'manager_id')->textInput() ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'date_create')->textInput() ?>

    <?= $form->field($model, 'date_close')->textInput() ?>

    <?= $form->field($model, 'project_type')->textInput() ?>

    <?= $form->field($model, 'comment')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'total')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'profit')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'status')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/projects/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Projects');
//$this->params['breadcrumbs'][] = $this->title;
?>

    <div class="options">
        <div class="choose-country d-sm-none d-md-none d-lg-none d-xl-none" id="country-click">
            <a href="#" class="choose-country-click">Choose Projects <span><i class="fas fa-caret-right"></i></span></a>
            <ul id="sm-countries">
                <li><a href="/projects/create"><i class="fa fa-plus" aria-hidden="true"></i> Add Project</a></li>
                <li><a href="/projects/index"><i class="fa fa-bars" aria-hidden="true"></i> All Projects</a></li>
                <!-- <li><a href="/projects/profit"><i class="fa fa-thumbs-up" aria-hidden="true"></i> Total month profit</a></li> -->
            </ul>
        </div>

        <ul id="countries">
            <li><a href="/projects/create" class="btn-add-client"><i class="fa fa-plus" aria-hidden="true"></i> Add Project</a></li>
            <li><a href="/projects/index"><i class="fa fa-bars" aria-hidden="true"></i> All Projects</a></li>
            <!-- <li><a href="/projects/profit"><i class="fa fa-thumbs-up" aria-hidden="true"></i> Total month profit</a></li> -->
        </ul>
    </div>

    <section class="all-cargos-content">
        <div class="container-fluid">
            <div class="row no-fw-row">

                <div class="col-sm-6">
                    <div class="all-cargos-title">
                        All Projects *
                    </div>
                    <!-- <div class="sorting">
                        <div class="sorting-title">sorting</div>
                        <div class="picked-sorting">Projects date recelved <i class="fas fa-caret-down"></i> <a href="#"><img src="/web/img/cancel-icon.png" alt="#"></a></div>
                    </div> -->
                </div>

                <div class="col-sm-6 all-cargos-buttons">
                    <div class="add-new">
                        <!-- <div class="ad-search">
                            <a href="#"><i class="fas fa-search"></i></a>
                        </div>
                        <div class="ad-button">
                            <a href="#"><i class="fas fa-plus"></i> Add</a>
                        </div>
                        <div class="ad-menu">
                            <a href="#"><i class="fas fa-bars"></i></a>
                        </div> -->
                    </div>
                </div>

                <div class="table-wrap">
                    <table class="table table-striped table-bordered table-resizable custom-tab">
                        <thead>
                                <tr>
                                    <th>Project ID</th>
                                    <th>Manager</th>
                                    <th>Client</th>
                                    <th>Project Created</th>
                                    <th>Project Closed</th>
                                    <th>Project Type</th>
                                    <th>Delivery type</th>
                                    <th>Project name</th>
                                    <th>Comments</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?= $all_table_rows ?>
                            </tbody>
                    </table>
                </div>

                <div class="detail-info-top-line">

                    <div class="detail-info-controls">
                        <a href="#" id="slide-left"><img src="/web/img/arr-left.png" alt="#"></a>
                        <a href="#" id="slide-right"><img src="/web/img/arr-right.png" alt="#"></a>
                    </div>

                    <div class="detail-info-right-controls">
                        <div class="detail-info-right-controls-button">
                            <a href="/projects/edit/" class="projects-detail-info-url-edit"><img src="/web/img/pencil.png" alt="">Edit</a>
                            <!-- <a href="#"><img src="/web/img/duplicate-icon.png" alt="">Duplicate</a> -->
                            <a href="#" id="close-detail-info"><img src="/web/img/close-icon.png" alt=""></a>
                        </div>
                    </div>

                </div>

                <div class="detail-info-wrap">

                    <div class="detail-info">

                        <div class="detail-info-list-wrap">
                            <div class="detail-info-list-row">
                                <div class="detail-info-list-column column-grey">Project ID</div>
                                <div class="detail-info-list-column detail-info-id"></div>
                            </div>
                            <div class="detail-info-list-row">
                                <div class="detail-info-list-column column-grey">Manager</div>
                                <div class="detail-info-list-column detail-info-manager"></div>
                            </div>
                            <div class="detail-info-list-row">
                                <div class="detail-info-list-column column-grey">Client</div>
                                <div class="detail-info-list-column detail-info-client"></div>
                            </div>
                            <div class="detail-info-list-row">
                                <div class="detail-info-list-column column-grey">Project approved</div>
                                <div class="detail-info-list-column detail-info-status"></div>
                            </div>
                            <div class="detail-info-list-row">
                                <div class="detail-info-list-column column-grey">Project name</div>
                                <div class="detail-info-list-column detail-info-name"></div>
                            </div>
                            <div class="detail-info-list-row">
                                <div class="detail-info-list-column column-grey">Project Type</div>
                                <div class="detail-info-list-column detail-info-type"></div>
                            </div>
                            <div class="detail-info-list-row">
                                <div class="detail-info-list-column column-grey">Delivery type</div>
                                <div class="detail-info-list-column detail-info-delivery"></div>
                            </div>
                            <div class="detail-info-list-row">
                                <div class="detail-info-list-column column-grey">Comment</div>
                                <div class="detail-info-list-column detail-info-comment"></div>
                            </div>
                            <div class="detail-info-list-row">
                                <div class="detail-info-list-column column-grey">Project created</div>
                                <div class="detail-info-list-column detail-info-date"></div>
                            </div>
                            <div class="detail-info-list-row">
                                <div class="detail-info-list-column column-grey">Project closed</div>
                                <div class="detail-info-list-column detail-info-date_closed"></div>
                            </div>
                            <div class="detail-info-list-row">
                                <div class="detail-info-list-column column-grey">Total to pay</div>
                                <div class="detail-info-list-column detail-info-total"></div>
                            </div>
                            <div class="detail-info-list-row">
                                <div class="detail-info-list-column column-grey">Profit</div>
                                <div class="detail-info-list-column detail-info-profit"></div>
                            </div>
                        </div>

                    </div>

                </div>

            </div>
            <div class="row no-fw-row bt-row">
                <div class="col-6 showing">
                    Showing <?=$projectsCount?> of <?=$projectsCount?>
                </div>
                <div class="col-6 summary">
                    <!-- <img src="/web/img/list-icon.png" alt="#"> <a href="#">Show Summary</a> -->
                </div>
            </div>
        </div>
    </section>

<script type="text/javascript">
    $(window).resize(function() {
        tableHeight();
    });

    tableHeight();

    function tableHeight(){
        window_height = $(window).height();
        body_height = $('body').height();
        table = $('.table-wrap').height();
        summ_height = window_height - (body_height - table) - 15;
        $('.table-wrap').css({'max-height' : summ_height+'px'});
    }

    $('.mob-menu-Projects > a').addClass('active');

    /////////////////////////////////////////////////

    $(".table tbody .projects-row").on("click", function() {
        var cur_id = $(this).attr("data-project_id");
        var re, s;
        s = cur_id;
        re = /\D+/ig;
        index = s.replace(re, '');

        $('.detail-info').fadeOut(1000).removeClass("detail-visibe");
        $('.detail-info-top-line').animate({
            opacity: 1
        }, 700);
        $('.detail-info-top-line').css({
            "display": "flex"
        });
        $(".detail-info-wrap").find('.detail-info').fadeIn(700).addClass("detail-visibe");
        $('.projects-detail-info-url-edit').attr("href", '/projects/edit/' + $(this).attr("data-project_id"));
        $.ajax({ 
            type: 'GET', 
            url: '/projects/view/' + $(this).attr("data-project_id"), 
            data: {}, 
            dataType: 'json',
            success: function (data) { 
                $('.detail-info-id').text(data.project_id);
                $('.detail-info-manager').text(data.manager_id);
                $('.detail-info-client').text(data.client_id);
                $('.detail-info-status').text(data.status);
                $('.detail-info-name').text(data.name);
                $('.detail-info-type').text(data.project_type);
                $('.detail-info-delivery').text(data.delivery_type);
                $('.detail-info-comment').text(data.comment);
                $('.detail-info-date').text(data.date_create);
                $('.detail-info-date_closed').text(data.date_close);
                $('.detail-info-total').text(data.total);
                $('.detail-info-profit').text(data.profit);
                console.log(data);
            }
        });
    });
</script>

views/projects/menu.php
<div class="options">
    <div class="choose-country d-sm-none d-md-none d-lg-none d-xl-none" id="country-click">
        <a href="#" class="choose-country-click">Choose Projects <span><i class="fas fa-caret-right"></i></span></a>
        <ul id="sm-countries">
            <li><a href="/projects/create"><i class="fa fa-plus" aria-hidden="true"></i> Add Project</a></li>
            <li><a href="/projects/index"><i class="fa fa-bars" aria-hidden="true"></i> All Projects</a></li>
            <li><a href="/projects/paid"><i class="fas fa-check-circle"></i> Paid Projects</a></li>
            <li><a href="/projects/nopaid"><i class="fas fa-times-circle"></i> Unpaid Projects</a></li>
            <!-- <li><a href="/projects/profit"><i class="fa fa-thumbs-up" aria-hidden="true"></i> Total month profit</a></li> -->
        </ul>
    </div>

    <ul id="countries">
        <li><a href="/projects/create" class="btn-add-client"><i class="fa fa-plus" aria-hidden="true"></i> Add Project</a></li>
        <li><a href="/projects/index"><i class="fa fa-bars" aria-hidden="true"></i> All Projects</a></li>
        <li><a href="/projects/paid"><i class="fas fa-check-circle"></i> Paid Projects</a></li>
        <li><a href="/projects/nopaid"><i class="fas fa-times-circle"></i> Unpaid Projects</a></li>
        <!-- <li><a href="/projects/profit"><i class="fa fa-thumbs-up" aria-hidden="true"></i> Total month profit</a></li> -->
    </ul>
</div>

views/projects/one_table.php
<tr class="projects-row" data-project_id="<?= (!empty($project->project_id)) ? $project->project_id : '' ?>">
    
    <td><?= (!empty($project->project_id)) ? 'PRJ-'.$project->project_id : '' ?></td>
    <td><?= (!empty($project->manager->username)) ? $project->manager->username : '' ?></td>
    <td><?= (!empty($project->client->client_id)) ? '88-'.$project->client->client_id : '' ?><?= (!empty($project->client->name)) ? ' - '.$project->client->name : '' ?></td>
    <td><?= (!empty($project->date_create)) ? date('d.m.Y', $project->date_create) : '' ?></td>
    <td><?= (!empty($project->date_close)) ? date('d.m.Y', $project->date_close) : '' ?></td>
    <td><?= (!empty($project->project_type)) ? $project_Obj->type($project->project_type) : '' ?></td>
    <td><?= (!empty($project->shipmentType->name)) ? $project->shipmentType->name : '' ?></td>
    <td><?= (!empty($project->name)) ? $project->name : '' ?></td>
    <td class="table-description"><?= (!empty($project->comment)) ? $project->comment : '' ?></td>
</tr>

views/projects/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Project */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Projects'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="project-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a(Yii::t('app', 'Update'), ['update', 'id' => $model->project_id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('app', 'Delete'), ['delete', 'id' => $model->project_id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'project_id',
            'manager_id',
            'name',
            'date_create',
            'date_close',
            'project_type',
            'comment:ntext',
            'total',
            'profit',
            'status',
        ],
    ]) ?>

</div>